CREATE TABLE `activity` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tag` varchar(12) NOT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `warStars` int DEFAULT '0',
  `cwl` int DEFAULT '0',
  `clanCapitalContributions` int DEFAULT '0',
  `clanCapitalLoot` int DEFAULT '0',
  `donations` int DEFAULT '0',
  `donatedSpells` int DEFAULT '0',
  `donatedSiege` int DEFAULT '0',
  `clanPoints` int DEFAULT '0',
  `townHalls` int DEFAULT '0',
  `multiplayerWins` int DEFAULT '0',
  `defender` int DEFAULT '0',
  `builderHalls` int DEFAULT '0',
  `obstaclesRemoved` int DEFAULT '0',
  `goldGrab` bigint DEFAULT '0',
  `elixirGrab` bigint DEFAULT '0',
  `darkGrab` int DEFAULT '0',
  `wallBuster` int DEFAULT '0',
  `builderHuts` int DEFAULT '0',
  `mortars` int DEFAULT '0',
  `xbows` int DEFAULT '0',
  `infernos` int DEFAULT '0',
  `eagleArtillery` int DEFAULT '0',
  `scattershots` int DEFAULT '0',
  `spellTowers` int DEFAULT '0',
  `monolith` int DEFAULT '0',
  `weaponizedTH` int DEFAULT '0',
  `weaponizedHuts` int DEFAULT '0',
  `seasonChallenges` int DEFAULT '0',
  `superTroop` int DEFAULT '0',
  `warLoot` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `player` (`tag`),
  KEY `date` (`date`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
