CREATE TABLE `wars` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `teamSize` int(11) NOT NULL DEFAULT '0',
  `startTime` datetime NOT NULL,
  `endTime` datetime NOT NULL,
  `result` varchar(10) NOT NULL DEFAULT 'Ongoing',
  `clan1_tag` varchar(12) NOT NULL,
  `clan1_name` varchar(15) NOT NULL,
  `clan1_level` int(11) NOT NULL DEFAULT '0',
  `clan1_attacks` int(11) NOT NULL DEFAULT '0',
  `clan1_stars` int(11) NOT NULL DEFAULT '0',
  `clan1_destructionPercentage` decimal(10,0) NOT NULL DEFAULT '0',
  `clan2_tag` varchar(12) NOT NULL,
  `clan2_name` varchar(15) NOT NULL,
  `clan2_level` int(11) NOT NULL DEFAULT '0',
  `clan2_attacks` int(11) NOT NULL DEFAULT '0',
  `clan2_stars` int(11) NOT NULL DEFAULT '0',
  `clan2_destructionPercentage` decimal(10,0) NOT NULL DEFAULT '0',
  `war_status` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `war` (`startTime`,`clan1_tag`,`clan2_tag`),
  KEY `clan1` (`clan1_tag`),
  KEY `clan2` (`clan2_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
